---
title: "R Notebook"
output: html_notebook
---

```{r}
x<- c(1,2,3,4,5,6)
f_x <- replicate(6, 1/6)
barplot(f_x, names.arg = x, xlab = "x", ylab = "f(x)")
F_x <- cumsum(f_x)
plot(x, F_x, type = "s")
```


BERNOUILLI DISTRIBUTION:
```{r}
x<- c(0,1)
p_heads <- 0.6
f_x <- c(1 - p_heads, p_heads)
barplot(f_x, names.arg = x, xlab = "x", ylab = "f(x)")
```

BINOMIAL DISTRIBUTION:
```{r}
x<- seq(from= 0, to = 4, by = 1)
f_x <- dbinom(x = x, size = 4, prob = 1/6)
barplot(f_x, names.arg = x, xlab = "num of fives", ylab = "p(number of 5s")
```

```{r}
x<- seq(from= 0, to = 20, by = 1)
f_x <- pbinom(q = x, size = 20, prob = 0.5)
plot(x, f_x, type = "s")
```

```{r}
pbinom(q = 20, size = 20, prob = 0.5)

```

TASK:
```{r}
x <- c(0,1)
correct_ans <- 0.25
f_x <- c(1 - correct_ans, correct_ans)
barplot(f_x, names.arg = x)
```

```{r}
x <- seq(1, 20, by = 1)
f_x <- dbinom(x =x, size = 20, prob = 0.25)
barplot(f_x, names.arg = x, type = "s")
```

continuous uniform 

```{r}
l <- seq(0, 27, by = 0.01)
f_l <- dunif(x = l, min = 5, max = 22)
plot(l, f_l, xlab = "l mins", ylab = "F(l) prob density", type = "line")
```

```{r}
F_l <- punif(q = l, min = 5, max =22)
plot(x = l, y = F_l, type = "line")
```

