---
title: "R Notebook"
output: html_notebook
---


```{r}
library(httr)
```

```{r}
api_key <- source("api_key.R")
api_key
```
```{r}
?source
```

```{r}
response_1 <- GET(api_key[1], 
                query = list(
                  t = "Avatar"
                ))
response_1 <- content(response_1)
```

```{r}
response_2 <- GET(api_key[1], 
                query = list(
                  t = "Titanic"
                ))
response_2<- content(response_2)
```

```{r}
response_3 <- GET(api_key[1], 
                query = list(
                  t = "Diehard"
                ))
response_3 <- content(response_3)
```

```{r}
response_4 <- GET(api_key[1], 
                query = list(
                  t = "Batman"
                ))
response_4 <- content(response_4)
```

```{r}
response_5 <- GET(api_key[1], 
                query = list(
                  t = "Avengers"
                ))
response_5 <- content(response_5)
```

```{r}
list_of_5 <- c(response_1, response_2, response_3, response_4, response_5)
data.frame(list_of_5)
```

